# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Application

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn run build

    - name: calculate short sha
      shell: bash
      run: echo "git_short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: tarball the build
      shell: bash
      run: tar czvf twatter-${{ env.git_short_sha }}.tar.gz .next/ dist/

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: twatter-${{ env.git_short_sha }}.tar.gz
        path: ./twatter-${{ env.git_short_sha }}.tar.gz

  #deploy:
  #  needs: [build]
  #  runs-on: ubuntu-latest
    
        
  #  strategy:
